FROM mongo:5.0.9

# change bellow of environment variables
ENV MONGO_INITDB_ROOT_USERNAME="vod_analyzer_admin"
ENV MONGO_INITDB_ROOT_PASSWORD="rdxRo7U4turjJDVXDimLnKvUcW6XFRza4kYOd5JYsEh6ZADG48mM67H91b8f6QMj"
